[package]
name = "inner-circles-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dependencies.inner-circles]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.5"
